### PR TITLE
Fix exercise bug

### PR DESCRIPTION
**Pull request by haythem96**
This pull request fix the multiple vault exercise bug.

### CODE REVIEW

**Comment by antoncoding** [comment]
Can we just take the part that calculate the amount underlying to payout outside of the for loop? (for both ERC20 and ETH underlying), that way we only use the for loop to reduce amounts in vaults data structure.

```javascript
function exercise(vaults, otokenAmount) {

 // update data structure first
 let amountLeftToExercise = amountToPay;
 for (let vault of vaults) {
    if (vault.oTokensIssued > amountLeft) {
       _exercise(vault, amountLeft);
    } else {
       amountLeftToExercise -= vault.oTokensIssued;
      _exercise(vault, vault.oTokensIssued)
   }

 // pull underlyings
 const amountToPay  = calculateUnderlyingToPay
 if (underlying == ETH) {
   require(msg.value  == amountToPay)
 } else {
  require(ERC20.transferFrom(msg.sender), this, amountToPay)
 }

  // sendback collateral
  

}
```

**Comment by haythem96** [comment]
> Can we just take the part that calculate the amount underlying to payout outside of the for loop? (for both ERC20 and ETH underlying), that way we only use the for loop to reduce amounts in vaults data structure.
> 
> ```js
> function exercise(vaults, otokenAmount) {
> 
>  // update data structure first
>  let amountLeftToExercise = amountToPay;
>  for (let vault of vaults) {
>     if (vault.oTokensIssued > amountLeft) {
>        _exercise(vault, amountLeft);
>     } else {
>        amountLeftToExercise -= vault.oTokensIssued;
>       _exercise(vault, vault.oTokensIssued)
>    }
> 
>  // pull underlyings
>  const amountToPay  = calculateUnderlyingToPay
>  if (underlying == ETH) {
>    require(msg.value  == amountToPay)
>  } else {
>   require(ERC20.transferFrom(msg.sender), this, amountToPay)
>  }
> 
>   // sendback collateral
>   
> 
> }
> ```

Can u explain more ? I didn't get that

**Comment by antoncoding** [comment]
> Can u explain more ? I didn't get that

So instead of transferring in underlying and paying out collateral in the internal `_exercise` function, we can only update the vault data structure in that internal function, and just pull underlying and payout the total collateral in the `exercise()` function. Because we can calculate the total amount to transfer in / payout, we don't have to do that a the loop.

**Comment by antoncoding** [comment]
It's better pattern to do
1. vault data update 
2. check underlying is transferred in (external calls)
3. transfer collateral (external calls)

**Comment by haythem96** [comment]
Closing this as we are replacing ETH  with WETH.

**Pull request closed without merging**
